name: Build and Sign macOS
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2

     # Install dependencies and build you app here #
     # - name: Build executable
     #     run: ---

      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |

      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          ls -la
          echo $MACOS_CERTIFICATE | base64 â€”-decode > certificate.p12
          ls -la
          security create-keychain -p $MACOS_CERTIFICATE_PWD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $MACOS_CERTIFICATE_PWD build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_CERTIFICATE_PWD build.keychain
          /usr/bin/codesign --force -s <identity-id> ./path/to/you/app -v
